# Generated by Django 4.1 on 2024-01-30 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
