# Generated by Django 4.1 on 2024-01-30 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_alter_sales_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(default='wriberpos@gmail.com', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
