# Generated by Django 4.1 on 2024-01-31 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0003_alter_sales_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='saleitemuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
