# Generated by Django 4.1 on 2024-01-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_salesitems_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cost_price',
            field=models.FloatField(default=0),
        ),
    ]
