# Generated by Django 4.1 on 2024-02-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_branch_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
