# Generated by Django 4.1 on 2024-04-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_ascetic_fluid_test_confirmed_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_performed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('lab_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labtestperformed', to='posApp.lab')),
            ],
        ),
    ]
