# Generated by Django 4.1 on 2024-04-01 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0013_test_performed'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_performed',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testsperformer', to=settings.AUTH_USER_MODEL),
        ),
    ]
