# Generated by Django 4.1 on 2024-04-01 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0014_test_performed_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_performed',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
