# Generated by Django 4.1 on 2024-04-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0016_customer_customersales_supplier_customersalesitems_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersales',
            name='terms_conditions',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productchange',
            name='suppliers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplierchangeproduct', to='posApp.supplier'),
        ),
    ]
