# Generated by Django 4.1 on 2024-05-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0020_customersales_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_performed',
            name='id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='testid', serialize=False, to='posApp.investigations'),
        ),
    ]
